// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xitaso_Webapplikation_DB.Data;

namespace Xitaso_Webapplikation_DB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210707184810_addAllColumnstoDataBase")]
    partial class addAllColumnstoDataBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Xitaso_Webapplikation_DB.Models.Analyse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProjektId")
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("lastChanged")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("projectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId");

                    b.ToTable("Analysen");
                });

            modelBuilder.Entity("Xitaso_Webapplikation_DB.Models.Analysekategorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("analyseId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("analyseId");

                    b.ToTable("Analysekategorien");
                });

            modelBuilder.Entity("Xitaso_Webapplikation_DB.Models.Frage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SollBewertung")
                        .HasColumnType("int");

                    b.Property<int>("analyseKategorieId")
                        .HasColumnType("int");

                    b.Property<int>("istBewertung")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("analyseKategorieId");

                    b.ToTable("Fragen");
                });

            modelBuilder.Entity("Xitaso_Webapplikation_DB.Models.Projekt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ProjectFinished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("projectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projekte");
                });

            modelBuilder.Entity("Xitaso_Webapplikation_DB.Models.Analyse", b =>
                {
                    b.HasOne("Xitaso_Webapplikation_DB.Models.Projekt", null)
                        .WithMany("analysis")
                        .HasForeignKey("ProjektId");
                });

            modelBuilder.Entity("Xitaso_Webapplikation_DB.Models.Analysekategorie", b =>
                {
                    b.HasOne("Xitaso_Webapplikation_DB.Models.Analyse", null)
                        .WithMany("analysekategories")
                        .HasForeignKey("analyseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Xitaso_Webapplikation_DB.Models.Frage", b =>
                {
                    b.HasOne("Xitaso_Webapplikation_DB.Models.Analysekategorie", null)
                        .WithMany("questions")
                        .HasForeignKey("analyseKategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Xitaso_Webapplikation_DB.Models.Analyse", b =>
                {
                    b.Navigation("analysekategories");
                });

            modelBuilder.Entity("Xitaso_Webapplikation_DB.Models.Analysekategorie", b =>
                {
                    b.Navigation("questions");
                });

            modelBuilder.Entity("Xitaso_Webapplikation_DB.Models.Projekt", b =>
                {
                    b.Navigation("analysis");
                });
#pragma warning restore 612, 618
        }
    }
}
